### ISSUE TITLE
Feature Request: Tracker and Meeting Section Development

### ISSUE THREAD

**Issue by shivang-16** [Leadlly/leadlly.mentor.mobileapp#2]
### **Feature Request: Tracker and Meeting Section Development**

We need to implement the **Tracker** and **Meeting Section** in the application as per the designs provided. This feature will enhance user engagement and facilitate efficient tracking and scheduling of meetings.

### **Design Reference**

Please refer to the Figma design for the layout and component structure:  
[Figma Prototype](https://www.figma.com/proto/mCkDijxysQSf6NdsTzaRy4/leadlly.in?node-id=8660-5497&node-type=frame&t=k5zIvWvhbV0YQYTd-0&scaling=scale-down&content-scaling=fixed&page-id=378%3A1212&starting-point-node-id=7983%3A5488&show-proto-sidebar=1)

Additionally, here is the link for images and assets needed for the implementation:  
[Assets and Images Resource](https://www.figma.com/design/mCkDijxysQSf6NdsTzaRy4/leadlly.in?node-id=8660-5497&node-type=frame&t=xR5jCc0LyxmG5ljV-0)

A video overview of the expected functionality is provided here:  

https://github.com/user-attachments/assets/4330c0a3-5b25-415f-940c-a2bc7b26c49f

### **Code Reference**

Refer to the [leadlly.student.mobileapp](https://github.com/Leadlly/leadlly.student.mobileapp) repository for reusable components and code patterns. You can directly take some of the components from there as they are already present and will streamline development.

### **API Integration**

The necessary APIs for this feature are already present in the [leadlly.mentor.api](https://github.com/Leadlly/leadlly.mentor.api/blob/main/README.md) repository. Please follow the setup instructions in the `contributing.md` file to get the API environment running locally. Full integration with these APIs is required for the feature.

### **Bounty**

A **$15 bounty** is available for completing this feature after proper implementation with API integration. Payment will be provided upon successful testing and deployment.

### **Setup Assistance**

If you face any issues during setup or development, feel free to reach out, and we will assist you in getting everything up and running.

**Comment by RajVerma97** [comment]
can you assign this to me? i  want to work on it

**Comment by shivang-16** [comment]
> can you assign this to me? i want to work on it

msg me here - https://x.com/16_shivang

**Comment by RajVerma97** [comment]
check your twitter app
